### ISSUE TITLE
file that cannot be opened

### ISSUE THREAD

**Issue by love56014** [Synthlight/MHR-Editor#8]
![unknown](https://user-images.githubusercontent.com/109636810/194888508-f7ffc87a-e3c5-438b-805c-e37d01075a32.png)

**Comment by love56014** [comment]
is this PlayerUserDataSkillParameter.user.2

**Comment by Synthlight** [comment]
The editor is perfectly capable of opening that file. If you're opening a mod with that file and get this error, then that file is from a previous MHR update and you will need the version of MHR-Editor that corresponds to that.

If you're opening a *new* file and get that error, that's because you didn't extract from `re_chunk_000.pak.patch_001.pak` which contains the newest title update data. The one from the base pak **will not work as it's outdated**.

Not a bug.
